# Generated by Django 5.0.3 on 2024-03-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeyboardEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
