# Generated by Django 5.0.3 on 2024-03-28 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mouse", "0002_keyboardevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KeyboardEvent",
        ),
    ]
